-- =============================================
-- Online Feedback Collection System - Schema
-- =============================================

CREATE DATABASE IF NOT EXISTS feedback_system
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE feedback_system;

-- ─── Users Table ──────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(100)  NOT NULL,
  email       VARCHAR(150)  NOT NULL UNIQUE,
  password    VARCHAR(255)  NOT NULL,
  role        ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  is_active   TINYINT(1)    NOT NULL DEFAULT 1,
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_email (email),
  INDEX idx_role  (role)
) ENGINE=InnoDB;

-- ─── Feedback Table ───────────────────────────
CREATE TABLE IF NOT EXISTS feedback (
  id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id     INT UNSIGNED  NOT NULL,
  category    ENUM('general','product','service','support','other') NOT NULL DEFAULT 'general',
  rating      TINYINT       NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title       VARCHAR(200)  NOT NULL,
  comment     TEXT          NOT NULL,
  status      ENUM('pending','reviewed','resolved') NOT NULL DEFAULT 'pending',
  admin_note  TEXT          NULL,
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX idx_user_id   (user_id),
  INDEX idx_category  (category),
  INDEX idx_status    (status),
  INDEX idx_rating    (rating),
  INDEX idx_created   (created_at)
) ENGINE=InnoDB;

-- ─── Seed Admin User ──────────────────────────
-- Password: Admin@123  (bcrypt hash — regenerated by server on first run)
INSERT IGNORE INTO users (name, email, password, role)
VALUES (
  'System Admin',
  'admin@feedback.com',
  '$2a$12$placeholder_will_be_replaced_by_server',
  'admin'
);
